### ISSUE TITLE
Need help understanding how to config

### ISSUE THREAD

**Issue by PeterAndreasson** [dblommesteijn/homebridge-goodwe-inverter#1]
**Describe Your Problem:**

Tyringe to use the plugin for my new Goodwe But oblygt gets 0 on everything. 
guess im missing out on how to configure it?
I just added the ip and left the rest on dafault…
Can you help me?
Regards
/Peter 
**Logs:**

```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**

```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:
* **Homebridge Version**: 
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**:

**Comment by dblommesteijn** [comment]
Hi @PeterAndreasson, Sure I can try to understand your issue. Could you provide any more information, as you've not included in your initial request. Thanks.

**Comment by dblommesteijn** [comment]
Could you tell me what the output of this says on the box where homebridge is installed please: 
```
/usr/bin/sfk 192.168.1.29 8899 -listen -noerror -timeout=1000 0x7f0375940049d5c2 -pure +xed "/[eol]//"
```

**Comment by PeterAndreasson** [comment]
I get:
bash: /usr/bin/sfk: No such file or directory

**Comment by dblommesteijn** [comment]
> I get:
> bash: /usr/bin/sfk: No such file or directory

In that case please revert to the readme how to setup sfk.

**Comment by PeterAndreasson** [comment]
Yep ive missed that little thing :)
Thanks for the support!

**Comment by dblommesteijn** [comment]
@PeterAndreasson you are welcome, good luck setting up!
