### ISSUE TITLE
SFK configuration problem

### ISSUE THREAD

**Issue by vinietu** [dblommesteijn/homebridge-goodwe-inverter#2]
**Describe Your Problem:**
Hello, I hope you will be able to give me some advise to figure it out. As you can see I also have values 0. I've installed SFK and when I'm running "/usr/bin/sfk 192.168.1.29 8899 -listen -noerror -timeout=1000 0x7f0375940049d5c2 -pure +xed "/[eol]//"" I got "bash: /usr/bin/sfk: Is a directory"
but when I run "sfk cudp 192.168.8.128 8899 -listen -noerror -timeout=1000 0x7f0375940049d5c2 -pure +xed "/[eol]//""
i got some response:
"AA557F03921708100D222C0DE6007C0DCF007CFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF1029103B1060096F095C095D007700790077138A13881386000021C60001000000000000000000000000000D0000000003E8FFFF01F4FFFFFFFF0133000005F10000002D00200000000000000000FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF000018AD0B7F000000040000046000000004000000236159"

I need to mention that when I'm using python script on my local network it connects and gets proper values from inverter.

Do you have any?

**Logs:**

```
16/08/2023, 13:26:58] [homebridge-goodwe-inverter] running cmd:  /usr/bin/sfk cudp 192.168.8.128 8899 -listen -noerror -timeout=1000 0x7f0375940049d5c2 -pure +xed "/[eol]//"
[16/08/2023, 13:26:58] [homebridge-goodwe-inverter] cmd:error 
[16/08/2023, 13:26:58] [homebridge-goodwe-inverter] parseInverter:output 
[16/08/2023, 13:26:58] [homebridge-goodwe-inverter] fetchPowerStationUpdate local-instance: 192.168.8.128:8899 with # 3 accessories
[16/08/2023, 13:26:58] [homebridge-goodwe-inverter] New value Current Production W 0
[16/08/2023, 13:26:58] [homebridge-goodwe-inverter] New value Day Production Wh 0
[16/08/2023, 13:26:58] [homebridge-goodwe-inverter] New value Internal Temp C 0```

**Plugin Config:**

```json
            "localIps": [
                {
                    "localIp": "192.168.8.128",
                    "port": "8899",
                    "timeout": 1000,
                    "options": "0x7f0375940049d5c2"
                }
            ],
            "SFKLocation": "/usr/bin/sfk",
            "showCurrentPowerLevel": true,
            "showDayTotal": true,
            "showInternalTemperature": true,
            "_bridge": {
                "username": "0E:28:2E:DF:CA:B8",
                "port": 44099
            },
            "platform": "HomebridgeGoodWeInverter"
        }
    ],```

**Environment:**

* **Plugin Version**:latest
* **Homebridge Version**: <1.6.1>
* **Node.js Version**: <v18.16.0>
* **NPM Version**: <9.5.1>
* **Operating System**: <Raspbian>

**Comment by vinietu** [comment]
issue can be closed :) wrong installation folder of SFK, my fault.
now showing data.

**Comment by dblommesteijn** [comment]
Good to hear!
