### ISSUE TITLE
type of accessory in Homekit

### ISSUE THREAD

**Issue by vinietu** [dblommesteijn/homebridge-goodwe-inverter#3]
**Is your feature request related to a problem? Please describe:**
<Currently all values shown as a part of climate so you have to go to needed room>

**Describe the solution you'd like:**
<it will be perfect to change type to e.g. thermostat or light to see tile on the HK dashboard>

**Describe alternatives you've considered:**
<or make it configurable :) >

**Additional context:**
![IMG_2882](https://github.com/dblommesteijn/homebridge-goodwe-inverter/assets/142392567/738e0d25-ea93-4a48-9d6d-36f976236922)

**Comment by dblommesteijn** [comment]
Hello @vinietu do you want the accessory to be configurable? Are you referring to the temp sensor accessory or the production of energy?

**Comment by vinietu** [comment]
Hello @dblommesteijn thanks for replay. I think all values are important when it comes to such an important equipment so it will be perfect to see all three ones on a tile in HK. I saw in different inverter plugin that they are using lightbulb accessory to show data (https://github.com/longzheng/homebridge-fronius-inverter-lights#readme)

**Comment by dblommesteijn** [comment]
> Hello @dblommesteijn thanks for replay. I think all values are important when it comes to such an important equipment so it will be perfect to see all three ones on a tile in HK. I saw in different inverter plugin that they are using lightbulb accessory to show data (https://github.com/longzheng/homebridge-fronius-inverter-lights#readme)

Sure I understand, this plugin is not as far as to show all data yet.
Furthermore, lightbulb accessories are controllable, so if you set the brightness HK expects a value to be set. However, the inverter is passive and will only show data (there is no way to control values), hence I opted for the light-sensor accessory.

**Comment by vinietu** [comment]
Yes yes I get it but it looks pretty good :) and there you have all data in your main dashboard. I'm also using this script from https://github.com/mletenay/home-assistant-goodwe-inverter and run inverter_test.py.
To sum up thanks for this plugin and if you ever consider upgrading it will be always very appreciated :)

**Comment by dblommesteijn** [comment]
> Yes yes I get it but it looks pretty good :) and there you have all data in your main dashboard. I'm also using this script from https://github.com/mletenay/home-assistant-goodwe-inverter and run inverter_test.py. To sum up thanks for this plugin and if you ever consider upgrading it will be always very appreciated :)

It does look good indeed.
I'll consider it when releasing the next version, thanks for the tip.
