### ISSUE TITLE
Communication block data sending to SEMS portal

### ISSUE THREAD

**Issue by vinietu** [dblommesteijn/homebridge-goodwe-inverter#4]
Hello @dblommesteijn again :)

**Describe The Bug:**
I noticed when I have enabled plugin the data to SEMS portal stop to send and what I can see on the portal is just last sent data. When I disable it data start to send and portal is up to date.

**To Reproduce:**
Now I'm using in my inverter wifi dongle and RSSI is below 30% and maybe this is the reason.

**Expected behavior:**
Is it possible using options field in plugin setting to increase time between refreshing data. Maybe this will help until I will change my dongle to wired one.

**Logs:**

```
in Homebringe pluging showing data correctly ```

**Plugin Config:**

```json
            "localIps": [
                {
                    "localIp": "192.168.8.105",
                    "port": "8899",
                    "timeout": 1000,
                    "options": "0x7f0375940049d5c2"
                }
            ],
            "SFKLocation": "/usr/bin/sfk",
            "showCurrentPowerLevel": true,
            "showDayTotal": true,
            "showInternalTemperature": true,
            "_bridge": {
                "username": "0E:28:2E:DF:CA:B8",
                "port": 44099
            },
            "platform": "HomebridgeGoodWeInverter"
        }
    ],```

**Environment:**

* **Plugin Version**:latest
* **Homebridge Version**: <1.6.1>
* **Node.js Version**: <v18.16.0>
* **NPM Version**: <9.5.1>
* **Operating System**: <Raspbian>

**Comment by vinietu** [comment]
or maybe you are able to provide first version of your plugin to homebridge to use data directly from SEMS portal

**Comment by dblommesteijn** [comment]
> or maybe you are able to provide first version of your plugin to homebridge to use data directly from SEMS portal

Well the problem with the SEMS portal is their API does not allow for quick refreshing, I lost my access to my account for over 1 month because of rate-limiting, as they were not able to recover it quickly at GoodWe. So I do not suggest this route.

You can increase the timeout setting to 5000 (which is 5 seconds), perhaps this will be more stable?

PS. I am working on a new release with fixes like this, as I have the same issues.

**Comment by vinietu** [comment]
Wow nice to hear that, can't wait to use this new version. And with your suggestions I will test today. Thanks again!

**Comment by vinietu** [comment]
Hello @dblommesteijn  unfortunately changing timeout in settings didn't help even for 15000. If you will need tester for a new version just let me know ;)

**Comment by vinietu** [comment]
Hello @dblommesteijn 
I've changed in platform.js value from 10000 to 100000:
this.retry[localInstanceConfig.localIp]++;
            await this.sleep(**100000**, () => {
                this.log.debug('sleeping...');
and I have data after every 100s and SEMS portal is working fine

**Comment by vinietu** [comment]
Hello @dblommesteijn 
I've noticed that SEMS portal is refreshing every 5minutes so I changed value in platform.js from 10000ms to 305000ms:

    async discoverDevices() {
        for (const localInstanceConfig of this.config.localIps) {
            const accessories = [];
            const inverterData = await this.lookupLocalInstance(localInstanceConfig);
            if (this.config.showCurrentPowerLevel) {
                accessories.push(this.loadElectricityAccessory(localInstanceConfig, inverterData, ['power'], 'Current Production W'));
            }
            if (this.config.showDayTotal) {
                accessories.push(this.loadElectricityAccessory(localInstanceConfig, inverterData, ['generationToday'], 'Day Production Wh'));
            }
            if (this.config.showInternalTemperature) {
                accessories.push(this.loadTemperatureAccessory(localInstanceConfig, inverterData, ['internalTemperature'], 'Internal Temp C'));
            }
            this.fetchLocalInstanceUpdate(**305000**, localInstanceConfig, accessories);

Now it looks like data are refreshing in SEMS portal and I have them on dashboard. Data are not so fresh but this is only workaround I found.
