### ISSUE TITLE
Is this plugin being developed? 

### ISSUE THREAD

**Issue by msegzda** [dblommesteijn/homebridge-goodwe-inverter#5]
Would be nice to hear about current state of its development

**Comment by dblommesteijn** [comment]
> Would be nice to hear about current state of its development

Yes, any reason to ask?
I am running this in my home setup without hiccups.

**Comment by msegzda** [comment]
I'm buying GoodWe inverter and preparing to use it on own automations. Wondering if this plugin would be good fit or should I write a new one. 

* Latest mod was months ago
* README.md is random (looks to be from plugin template)
* Plugin is not willing to become "homebridge verified"

Hence the questions.

Thank you for quick reply.

**Comment by vinietu** [comment]
Looks @msegzda you are new in hombridge and 1 month of last uodate is a great score. I'm using it since last year and do not care about verification however I can't wait to see your verified plugin. I can even provide some nice examples ;)
